title: Hehe!
description: > # this means to ignore newlines until "baseurl:"
  Hello, this website is made for upload my learnings or daily events
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gim Yeongjin # add your name
author-img:  # add your photo
about-author: Developer studying at HYU, SOCC. # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: smilu97 # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
